SELECT XSDDH,SUM(JE)
FROM (
select A.KNUMV AS PZTJH,A.KPOSN AS HXM,B.KNUMV,A.KSCHL AS LX,A.KBETR AS JE,B.VBELN AS XSDDH
from sapabap1.PRCD_ELEMENTS A
left join SAPABAP1.VBAK B
ON A.KNUMV=B.KNUMV
WHERE A.KSCHL='ZPT0' AND A.KPOSN=000000
UNION ALL
select A.KNUMV AS PZTJH,A.KPOSN AS HXM,B.KNUMV,A.KSCHL AS LX,A.KBETR AS JE,B.VBELN AS XSDDH
from sapabap1.PRCD_ELEMENTS A
left join SAPABAP1.VBAK B
ON A.KNUMV=B.KNUMV
WHERE A.KSCHL='ZYF0' AND A.KPOSN=000000
UNION ALL
select A.KNUMV AS PZTJH,A.KPOSN AS HXM,B.KNUMV,A.KSCHL AS LX,A.KWERT AS JE ,B.VBELN AS XSDDH
from sapabap1.PRCD_ELEMENTS A
left join SAPABAP1.VBAK B
ON A.KNUMV=B.KNUMV
WHERE A.KSCHL='ZPR1'
) T
GROUP BY XSDDH